### PR TITLE
Added skip functionality

### PR DESCRIPTION
**Pull request by shanel262**
Limits tests now pass. sqlite now has skip functionality

### CODE REVIEW

**Comment by shanel262** [comment]
@mihaidma Made a small fix

**Comment by mihaidma** [comment]
the change looks ok but the tests fail

**Comment by shanel262** [comment]
I'll let you know when I have it fixed

**Comment by mihaidma** [comment]
Please put a space before the LIMIT and OFFSET strings.

**Comment by shanel262** [comment]
@mihaidma Ok fixed, do you want me to squash the commits?

**Comment by mihaidma** [comment]
yes, please :)

**Pull request closed without merging**
